import {Field} from '@/types';
export interface ResourceConfig{key:string;endpoint:string;fields:Field[];columns:string[]}
export const configs:Record<string,ResourceConfig>={
  companies:{key:'companies',endpoint:'/companies',columns:['name','code','email','status'],fields:[{name:'name',required:true},{name:'code',required:true},{name:'email',type:'email',required:true},{name:'phone',required:true},{name:'address',required:true},{name:'logoUrl'},{name:'status',type:'select',options:['ACTIVE','INACTIVE']}]},
  departments:{key:'departments',endpoint:'/departments',columns:['name','code','description'],fields:[{name:'name',required:true},{name:'code',required:true},{name:'description',type:'textarea'}]},
  positions:{key:'positions',endpoint:'/positions',columns:['name','code','department'],fields:[{name:'departmentId',type:'select',lookup:'departments',required:true},{name:'name',required:true},{name:'code',required:true},{name:'description',type:'textarea'}]},
  employees:{key:'employees',endpoint:'/employees',columns:['fullName','employeeCode','department','position','status'],fields:[{name:'fullName',required:true},{name:'employeeCode',required:true},{name:'email',type:'email',required:true},{name:'phone'},{name:'address'},{name:'departmentId',type:'select',lookup:'departments',required:true},{name:'positionId',type:'select',lookup:'positions',required:true},{name:'hireDate',type:'date'},{name:'status',type:'select',options:['ACTIVE','INACTIVE']},{name:'password',type:'password'}]},
  meetings:{key:'meetings',endpoint:'/meetings',columns:['title','startAt','location','status'],fields:[{name:'title',required:true},{name:'description',type:'textarea'},{name:'location'},{name:'meetingUrl'},{name:'startAt',type:'datetime-local',required:true},{name:'endAt',type:'datetime-local',required:true},{name:'status',type:'select',options:['SCHEDULED','COMPLETED','CANCELLED']}]},
  projects:{key:'projects',endpoint:'/projects',columns:['name','code','status','startDate'],fields:[{name:'name',required:true},{name:'code',required:true},{name:'description',type:'textarea'},{name:'startDate',type:'date'},{name:'endDate',type:'date'},{name:'status',type:'select',options:['PLANNING','ACTIVE','COMPLETED','CANCELLED']}]},
  issues:{key:'issues',endpoint:'/issues',columns:['title','project','assignee','priority','status','dueDate'],fields:[{name:'projectId',type:'select',lookup:'projects',required:true},{name:'title',required:true},{name:'description',type:'textarea'},{name:'assigneeId',type:'select',lookup:'employees',required:true},{name:'priority',type:'select',options:['LOW','MEDIUM','HIGH','URGENT']},{name:'status',type:'select',options:['OPEN','IN_PROGRESS','DONE','CANCELLED']},{name:'dueDate',type:'date'}]},
  bulletins:{key:'bulletins',endpoint:'/bulletins',columns:['title','publishedAt','createdAt'],fields:[{name:'title',required:true},{name:'content',type:'textarea',required:true},{name:'publishedAt',type:'datetime-local'}]},
  notifications:{key:'notifications',endpoint:'/notifications',columns:['title','message','createdAt'],fields:[{name:'title',required:true},{name:'message',type:'textarea',required:true}]},
};
