'use client';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {ChevronLeft,ChevronRight,Eye,Pencil,Plus,Search,Trash2,UserPlus,X} from 'lucide-react';
import {useTranslations} from 'next-intl';
import {useState} from 'react';
import {toast} from 'sonner';
import {api} from '@/lib/api/client';
import {Item} from '@/types';
import {ResourceConfig} from './config';
import {ResourceForm} from './resource-form';

type Mode='create'|'edit'|'view'|'delete'|'admin'|null;
const adminConfig:ResourceConfig={key:'companies',endpoint:'/companies',columns:[],fields:[{name:'fullName',required:true},{name:'email',type:'email',required:true},{name:'password',type:'password',required:true}]};
const display=(value:unknown,t:(key:string)=>string)=>{if(value==null||value==='')return '—';if(typeof value==='object'){if('name' in value)return String((value as {name:unknown}).name);if('fullName' in value)return String((value as {fullName:unknown}).fullName)}if(typeof value==='string'&&['ACTIVE','INACTIVE','PLANNING','COMPLETED','CANCELLED','SCHEDULED','OPEN','IN_PROGRESS','DONE','LOW','MEDIUM','HIGH','URGENT'].includes(value))return <span className="badge">{t(`statuses.${value}`)}</span>;if(typeof value==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(value))return new Date(value).toLocaleString();return String(value)};

export function CrudPage({config}:{config:ResourceConfig}){
  const t=useTranslations();const queryClient=useQueryClient();const[page,setPage]=useState(1);const[search,setSearch]=useState('');const[query,setQuery]=useState('');const[mode,setMode]=useState<Mode>(null);const[selected,setSelected]=useState<Item>();
  const list=useQuery({queryKey:[config.key,page,query],queryFn:()=>api.get<Item[]>(`${config.endpoint}?page=${page}&pageSize=10&search=${encodeURIComponent(query)}`)});
  const save=useMutation({mutationFn:(data:Record<string,string>)=>mode==='admin'&&selected?api.post(`${config.endpoint}/${selected.id}/admin`,data):mode==='edit'&&selected?api.patch(`${config.endpoint}/${selected.id}`,data):api.post(config.endpoint,data),onSuccess:()=>{toast.success(t(mode==='admin'?'toast.adminCreated':'toast.saved'));setMode(null);void queryClient.invalidateQueries({queryKey:[config.key]})},onError:e=>toast.error(e.message)});
  const remove=useMutation({mutationFn:()=>api.delete(`${config.endpoint}/${selected?.id}`),onSuccess:()=>{toast.success(t('toast.deleted'));setMode(null);void queryClient.invalidateQueries({queryKey:[config.key]})},onError:e=>toast.error(e.message)});
  const open=(nextMode:Mode,item?:Item)=>{setSelected(item);setMode(nextMode)};const body=list.data?.data??[];const meta=list.data?.meta;
  return <section>
    <div className="flex flex-wrap items-center justify-between gap-3 mb-6"><div><h1 className="text-2xl font-bold">{t(`${config.key}.title`)}</h1><p className="text-gray-500 mt-1">{t(`${config.key}.description`)}</p></div><button className="btn btn-primary" onClick={()=>open('create')}><Plus size={18}/>{t('common.actions.create')}</button></div>
    <div className="card overflow-hidden">
      <form className="p-4 border-b border-gray-200 flex gap-2" onSubmit={event=>{event.preventDefault();setPage(1);setQuery(search)}}><div className="relative flex-1 max-w-md"><Search className="absolute left-3 top-3 text-gray-400" size={18}/><input className="input pl-10" value={search} onChange={event=>setSearch(event.target.value)} placeholder={t('common.search')}/></div><button className="btn btn-secondary">{t('common.searchButton')}</button></form>
      {list.isLoading?<div className="p-12 text-center">{t('common.loading')}</div>:list.isError?<div className="p-12 text-center text-red-600">{t('common.error')}</div>:body.length===0?<div className="p-12 text-center text-gray-500">{t('common.empty')}</div>:<div className="overflow-x-auto"><table className="responsive-table w-full"><thead className="bg-gray-50"><tr>{config.columns.map(column=><th key={column} className="text-left p-3 text-sm text-gray-600">{t(`fields.${column}`)}</th>)}<th className="p-3 text-right">{t('common.actions.title')}</th></tr></thead><tbody>{body.map(row=><tr key={row.id} className="border-t border-gray-100">{config.columns.map(column=><td key={column} data-label={t(`fields.${column}`)} className="p-3">{display(row[column],t)}</td>)}<td data-label={t('common.actions.title')} className="p-3"><div className="flex justify-end gap-1">{config.key==='companies'&&<button className="btn btn-secondary p-2" title={t('common.actions.createAdmin')} onClick={()=>open('admin',row)}><UserPlus size={16}/></button>}<button className="btn btn-secondary p-2" title={t('common.actions.view')} onClick={()=>open('view',row)}><Eye size={16}/></button><button className="btn btn-secondary p-2" title={t('common.actions.edit')} onClick={()=>open('edit',row)}><Pencil size={16}/></button><button className="btn btn-danger p-2" title={t('common.actions.delete')} onClick={()=>open('delete',row)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>}
      <div className="p-4 border-t border-gray-200 flex items-center justify-between"><span className="text-sm text-gray-500">{t('pagination.summary',{page:meta?.page??1,total:meta?.totalPages??1,items:meta?.totalItems??0})}</span><div className="flex gap-2"><button className="btn btn-secondary p-2" disabled={page<=1} onClick={()=>setPage(value=>value-1)}><ChevronLeft size={18}/></button><button className="btn btn-secondary p-2" disabled={!meta||page>=meta.totalPages} onClick={()=>setPage(value=>value+1)}><ChevronRight size={18}/></button></div></div>
    </div>
    {mode&&<div className="modal-bg" role="dialog" aria-modal="true"><div className="modal"><div className="flex justify-between items-center mb-5"><h2 className="text-xl font-bold">{t(`common.modal.${mode}`)} · {t(`${config.key}.title`)}</h2><button onClick={()=>setMode(null)}><X/></button></div>{mode==='view'&&selected?<dl className="grid md:grid-cols-2 gap-4">{config.fields.filter(field=>field.name!=='password').map(field=><div key={field.name}><dt className="text-sm text-gray-500">{t(`fields.${field.name}`)}</dt><dd className="font-medium mt-1">{display(selected[field.name],t)}</dd></div>)}</dl>:mode==='delete'?<><p>{t('common.deleteConfirm')}</p><div className="flex justify-end gap-2 mt-6"><button className="btn btn-secondary" onClick={()=>setMode(null)}>{t('common.actions.cancel')}</button><button className="btn btn-danger" onClick={()=>remove.mutate()} disabled={remove.isPending}>{t('common.actions.delete')}</button></div></>:<ResourceForm key={`${mode}-${selected?.id??'new'}`} config={mode==='admin'?adminConfig:config} item={mode==='edit'?selected:undefined} onSubmit={data=>save.mutate(data)} onCancel={()=>setMode(null)} busy={save.isPending}/>}</div></div>}
  </section>;
}
