'use client';
import {zodResolver} from '@hookform/resolvers/zod';
import {Building2,Languages} from 'lucide-react';
import {useLocale,useTranslations} from 'next-intl';
import {useState} from 'react';
import {useForm} from 'react-hook-form';
import {z} from 'zod';
import {useAuth} from '@/features/auth/auth-context';
import {usePathname,useRouter} from '@/i18n/navigation';
const schema=z.object({email:z.email(),password:z.string().min(8)});type Form=z.infer<typeof schema>;
export default function Login(){const t=useTranslations();const{login}=useAuth();const[error,setError]=useState('');const locale=useLocale();const router=useRouter();const path=usePathname();const{register,handleSubmit,formState:{errors,isSubmitting}}=useForm<Form>({resolver:zodResolver(schema),defaultValues:{email:'admin@company1.com',password:'Demo@123'}});const submit=async(v:Form)=>{try{setError('');await login(v.email,v.password)}catch(e){setError(e instanceof Error?e.message:t('common.error'))}};return <main className="min-h-screen grid lg:grid-cols-2"><section className="hidden lg:flex bg-blue-700 text-white p-16 flex-col justify-between"><Building2 size={46}/><div><h1 className="text-4xl font-bold mb-4">{t('app.name')}</h1><p className="text-blue-100 text-lg">{t('auth.tagline')}</p></div><small>© 2026</small></section><section className="flex items-center justify-center p-5 relative"><button className="btn btn-secondary absolute top-5 right-5" onClick={()=>router.replace(path,{locale:locale==='vi'?'en':'vi'})}><Languages size={16}/>{locale==='vi'?'EN':'VI'}</button><form onSubmit={handleSubmit(submit)} className="card p-7 w-full max-w-md"><h2 className="text-2xl font-bold mb-2">{t('auth.login')}</h2><p className="text-gray-500 mb-6">{t('auth.subtitle')}</p><label className="label">{t('fields.email')}</label><input className="input" {...register('email')}/>{errors.email&&<p className="error">{t('validation.email')}</p>}<label className="label mt-4">{t('fields.password')}</label><input className="input" type="password" {...register('password')}/>{errors.password&&<p className="error">{t('validation.min8')}</p>}{error&&<p className="error mt-4">{error}</p>}<button className="btn btn-primary w-full mt-6" disabled={isSubmitting}>{isSubmitting?t('common.loading'):t('auth.login')}</button><p className="text-xs text-gray-500 mt-4">{t('auth.demoHint')}</p></form></section></main>}
