'use client';
import {useQuery} from '@tanstack/react-query';
import {Bell,Building2,CalendarDays,FolderKanban,Network,Newspaper,Users} from 'lucide-react';
import {useTranslations} from 'next-intl';
import {api} from '@/lib/api/client';
import {useAuth} from '@/features/auth/auth-context';
const iconMap={totalCompanies:Building2,activeCompanies:Building2,totalDepartments:Network,totalEmployees:Users,totalProjects:FolderKanban,upcomingMeetings:CalendarDays,totalBulletins:Newspaper,totalNotifications:Bell};
export default function Dashboard(){const t=useTranslations();const{user}=useAuth();const q=useQuery({queryKey:['dashboard'],queryFn:()=>api.get<Record<string,unknown>>('/dashboard'),enabled:!!user});const data=q.data?.data??{};const keys=user?.role==='SUPER_ADMIN'?['totalCompanies','activeCompanies']:user?.role==='ADMIN'?['totalDepartments','totalEmployees','totalProjects','upcomingMeetings','totalBulletins','totalNotifications']:['totalProjects','upcomingMeetings'];return <section><h1 className="text-2xl font-bold">{t('dashboard.title')}</h1><p className="text-gray-500 mt-1 mb-6">{t('dashboard.welcome',{name:user?.employee?.fullName??user?.email??''})}</p>{q.isLoading?<p>{t('common.loading')}</p>:q.isError?<p className="text-red-600">{t('common.error')}</p>:<><div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-4">{keys.map(k=>{const Icon=iconMap[k as keyof typeof iconMap];return <article className="card p-5" key={k}><div className="flex justify-between"><div><p className="text-sm text-gray-500">{t(`dashboard.cards.${k}`)}</p><strong className="text-3xl mt-2 block">{String(data[k]??0)}</strong></div><span className="bg-blue-50 text-blue-600 p-3 rounded-xl h-fit"><Icon/></span></div></article>})}</div>{user?.role==='SUPER_ADMIN'&&Array.isArray(data.recentCompanies)&&<div className="card p-5 mt-6"><h2 className="font-bold mb-4">{t('dashboard.recentCompanies')}</h2>{data.recentCompanies.map((x:unknown)=><p className="py-2 border-b border-gray-100" key={(x as {id:string}).id}>{(x as {name:string}).name}</p>)}</div>}{user?.role==='EMPLOYEE'&&<div className="grid lg:grid-cols-2 gap-4 mt-6"><Recent title={t('dashboard.recentBulletins')} items={data.recentBulletins}/><Recent title={t('dashboard.recentNotifications')} items={data.recentNotifications}/></div>}</>}</section>}
function Recent({title,items}:{title:string;items:unknown}){return <div className="card p-5"><h2 className="font-bold mb-3">{title}</h2>{Array.isArray(items)&&items.length?items.map((x:unknown)=><p className="py-2 border-b border-gray-100" key={(x as {id:string}).id}>{(x as {title:string}).title}</p>):<p className="text-gray-500">—</p>}</div>}
